- name: Restart DHCP
  service:
    name: isc-dhcp-server
    state: restarted

- name: Restart BIND
  service:
    name: bind9
    state: restarted

- name: Save iptables
  shell: iptables-save > /etc/iptables/rules.v4
