- hosts: zabbix
  become: yes
  roles:
    - role: geerlingguy.mysql 
      mysql_root_password: root

    - role: community.zabbix.zabbix_server
      zabbix_server_database: mysql
      zabbix_server_database_long: mysql
      zabbix_server_dbport: 3306
      zabbix_server_dbpassword: root