- name: Install necessary packages
  apt:
    name:
      - iptables
      - isc-dhcp-server
      - bind9
    update_cache: yes
    state: present

- name: Ensure IP forwarding is enabled in sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^net.ipv4.ip_forward"
    line: "net.ipv4.ip_forward = 1"
    state: present

- name: Apply sysctl settings from sysctl.conf
  command: sysctl -p

- name: Add POSTROUTING rule to iptables
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE
    out_interface: enp0s3
  notify:
    - Save iptables

- name: Ensure iptables rules directory exists
  file:
    path: /etc/iptables
    state: directory
    mode: "0755"

- name: Configure DHCP
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify:
    - Restart DHCP

- name: Configure DNS
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
    - Restart BIND

- name: Add DNS zone file
  template:
    src: db.devops.com.j2
    dest: /etc/bind/db.devops.com
  notify:
    - Restart BIND
